In [34]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("hershyandrew/amzn-dpz-btc-ntfx-adjusted-may-2013may2019")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\admin\.cache\kagglehub\datasets\hershyandrew\amzn-dpz-btc-ntfx-adjusted-may-2013may2019\versions\1

Between AMZN, DPZ, BTC, and NFLX, which asset had the highest percentage growth from the first date to the last date?

In [35]:
import pandas as pd
import numpy as np

In [36]:
import os

os.listdir(path)

['portfolio_data.csv']

In [37]:
df = pd.read_csv(os.path.join(path, "portfolio_data.csv"), sep=",")

In [38]:
df

           Date         AMZN         DPZ          BTC        NFLX
0      5/1/2013   248.229996   51.190983   106.250000   30.415714
1      5/2/2013   252.550003   51.987320    98.099998   30.641428
2      5/3/2013   258.049988   52.446388   112.900002   30.492857
3      5/6/2013   255.720001   53.205257   109.599998   30.098572
4      5/7/2013   257.730011   54.151505   113.199997   29.464285
...         ...          ...         ...          ...         ...
1515   5/8/2019  1917.770020  283.149994  6171.959961  364.369995
1516   5/9/2019  1899.869995  282.160004  6358.290039      362.75
1517  5/10/2019  1889.979980  278.369995  7191.359863  361.040009
1518  5/13/2019  1822.680054  273.880005  7980.129883   345.26001
1519  5/14/2019  1840.119995  272.859985  8183.830078  345.609985

[1520 rows x 5 columns]

In [39]:
df.describe()

              AMZN          DPZ           BTC
count  1520.000000  1520.000000   1520.000000
mean    821.541810   146.771695   2421.465669
std     518.442653    72.192287   3310.894199
min     248.229996    51.190983     69.660004
25%     364.360001    84.993593    340.904999
50%     686.459992   127.168053    625.304993
75%    1121.287536   202.454994   3874.912415
max    2039.510010   298.635986  18972.320310

In [40]:
df.columns

Index(['Date', 'AMZN', 'DPZ', 'BTC', 'NFLX'], dtype='str')

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1520 non-null   str
 1   AMZN    1520 non-null   float64
 2   DPZ     1520 non-null   float64
 3   BTC     1520 non-null   float64
 4   NFLX    1520 non-null   str
dtypes: float64(3), str(2)
memory usage: 59.5 KB

In [44]:
df

           Date         AMZN         DPZ          BTC        NFLX
0      5/1/2013   248.229996   51.190983   106.250000   30.415714
1      5/2/2013   252.550003   51.987320    98.099998   30.641428
2      5/3/2013   258.049988   52.446388   112.900002   30.492857
3      5/6/2013   255.720001   53.205257   109.599998   30.098572
4      5/7/2013   257.730011   54.151505   113.199997   29.464285
...         ...          ...         ...          ...         ...
1515   5/8/2019  1917.770020  283.149994  6171.959961  364.369995
1516   5/9/2019  1899.869995  282.160004  6358.290039      362.75
1517  5/10/2019  1889.979980  278.369995  7191.359863  361.040009
1518  5/13/2019  1822.680054  273.880005  7980.129883   345.26001
1519  5/14/2019  1840.119995  272.859985  8183.830078  345.609985

[1520 rows x 5 columns]

In [47]:
df.dropna()

           Date         AMZN         DPZ          BTC        NFLX
0      5/1/2013   248.229996   51.190983   106.250000   30.415714
1      5/2/2013   252.550003   51.987320    98.099998   30.641428
2      5/3/2013   258.049988   52.446388   112.900002   30.492857
3      5/6/2013   255.720001   53.205257   109.599998   30.098572
4      5/7/2013   257.730011   54.151505   113.199997   29.464285
...         ...          ...         ...          ...         ...
1515   5/8/2019  1917.770020  283.149994  6171.959961  364.369995
1516   5/9/2019  1899.869995  282.160004  6358.290039      362.75
1517  5/10/2019  1889.979980  278.369995  7191.359863  361.040009
1518  5/13/2019  1822.680054  273.880005  7980.129883   345.26001
1519  5/14/2019  1840.119995  272.859985  8183.830078  345.609985

[1520 rows x 5 columns]

In [48]:
df.shape

(1520, 5)

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1520 entries, 0 to 1519
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1520 non-null   str
 1   AMZN    1520 non-null   float64
 2   DPZ     1520 non-null   float64
 3   BTC     1520 non-null   float64
 4   NFLX    1520 non-null   str
dtypes: float64(3), str(2)
memory usage: 59.5 KB